### ISSUE TITLE
1 Homepage

### ISSUE THREAD

**Issue by paul88543** [lyrasoft/hackathon#1]
# 頁面總覽
![landing page](https://user-images.githubusercontent.com/25097073/28746545-674d6df0-74c1-11e7-9b6b-87e30a3b9759.png)

![search](https://user-images.githubusercontent.com/25097073/28745294-34429ff2-74a8-11e7-8464-4f5a22aebc58.png)

(紅字為註解，請忽略)

## 全站搜尋：
Keyin關鍵字時會跳出類似關鍵字或標籤，版面參考 pinterest

- [x] 1. 建議選項：相關的 task 的 tag

- [x] 2. 建議選項 - Projects：相關的 Projects 名稱

- [x] 3. 建議選項 - Project Owners：相關的專案建立者名稱

![search](https://user-images.githubusercontent.com/25097073/28745161-d044ac6e-74a4-11e7-8711-95a2fc46937e.png)

## Tag：
Slider呈現，內文越長寬度會越長，間距固定 -> 參考 pinterest

![landing_page](https://user-images.githubusercontent.com/25097073/28745183-4f18c6e2-74a5-11e7-8893-4e0bdaefbab0.png)

## Task：

- [x] 1. 收藏 task

- [x] 2. task 縮圖

- [x] 3. Task name

- [x] 4.  觀看次數、收藏次數

- [x] 5. 星等：icon 與 評論（Awesome、Great Work... ）

- [x] 6. Hover 會有黑色遮罩（由下往上出現），並出現任務敘述與專案名稱

![landing_page](https://user-images.githubusercontent.com/25097073/28746547-6a2adbf2-74c1-11e7-9b75-956e640414ba.png)

## 隔線

- [x] 1. 全版

- [x] 2. 970px

![landing_page 3](https://user-images.githubusercontent.com/25097073/28745341-5b9d33e0-74a9-11e7-9a99-14baf881f941.png)
